version: '3'

services:
  consul-server-1:
    image: hashicorp/consul-enterprise:1.8.3-ent
    hostname: server-1
    container_name: server-1
    command: consul agent  -client 0.0.0.0  -data-dir="/consul/data"  -server -bootstrap-expect=3 -retry-join "server-2" -retry-join "server-3"

  consul-server-2:
    image: hashicorp/consul-enterprise:1.8.3-ent 
    hostname: server-2
    container_name: server-2
    command: consul agent  -client 0.0.0.0  -data-dir="/consul/data"  -server -bootstrap-expect=3 -retry-join "server-1" -retry-join "server-3"

  consul-server-3:
    image: hashicorp/consul-enterprise:1.8.3-ent 
    hostname: server-3
    container_name: server-3
    command: consul agent  -client 0.0.0.0  -data-dir="/consul/data"  -server -bootstrap-expect=3 -retry-join "server-1" -retry-join "server-2"




  consul-client-1:
    image: hashicorp/consul-enterprise:1.8.3-ent
    hostname: client-1
    container_name: client-1
    command: consul agent  -client 0.0.0.0  -data-dir="/consul/data"   -retry-join "server-1" -retry-join "server-2" -retry-join "server-3"

  consul-client-2:
    image: hashicorp/consul-enterprise:1.8.3-ent
    hostname: client-2
    container_name: client-2
    command: consul agent  -client 0.0.0.0  -data-dir="/consul/data"   -retry-join "server-1" -retry-join "server-2" -retry-join "server-3"